const SESSION_DURATION_SECONDS = 30 * 24 * 60 * 60
const SESSION_DURATION_MILLISECONDS = SESSION_DURATION_SECONDS * 1e3
const AUTH_BODY_SIZE_LIMIT = 2 ** 13
const RATE_LIMIT_RETRY_SECONDS = 60
const VERIFICATION_TOKEN_DURATION_SECONDS = 60 * 60
const VERIFICATION_TOKEN_DURATION_MILLISECONDS = VERIFICATION_TOKEN_DURATION_SECONDS * 1e3
const DUMMY_PASSWORD_HASH = '$scrypt$ln=14,r=8,p=5$dHYtZHVtbXktc2FsdC12MQ$T0cfJ5YYcprDlLOXBUN-l_9CEqACHnJN0a3hsu5XWQp2a3Wwe2-M-d-WfDZWw7WqJfvVCPIWCyAxofQPQKsZbw'

export {
  AUTH_BODY_SIZE_LIMIT,
  DUMMY_PASSWORD_HASH,
  RATE_LIMIT_RETRY_SECONDS,
  SESSION_DURATION_MILLISECONDS,
  SESSION_DURATION_SECONDS,
  VERIFICATION_TOKEN_DURATION_MILLISECONDS,
  VERIFICATION_TOKEN_DURATION_SECONDS
}
