packages:
  - apps/*
  - packages/*

saveExact: true

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  sharp: false
  workerd: false

minimumReleaseAgeExcludePrune: true

minimumReleaseAgeExclude:
  - '@cloudflare/workers-types@5.20260904.1'
