import * as v from 'valibot'
import type { CatalogEpisodeSource } from './catalog-episode-sources.ts'

const positiveInteger = v.pipe(v.number(), v.integer(), v.minValue(1), v.maxValue(2_147_483_647))
const dateSchema = v.pipe(v.string(), v.isoDate())

const episodeSchema = v.object({
  id: positiveInteger,
  season: positiveInteger,
  number: positiveInteger,
  name: v.nullable(v.string()),
  airdate: v.union([dateSchema, v.literal(''), v.null()])
})

const showSchema = v.object({
  id: positiveInteger,
  name: v.string(),
  premiered: dateSchema,
  language: v.string(),
  _embedded: v.object({ episodes: v.array(v.unknown()) })
})

const episodeSnapshotSchema = v.object({
  checkedOn: dateSchema,

  series: v.array(v.object({
    source: v.object({
      title: v.string(),
      year: positiveInteger,
      showId: positiveInteger,
      premiered: dateSchema,
      language: v.string(),
      seasonRestriction: v.nullable(positiveInteger)
    }),

    episodes: v.array(v.object({
      tvmazeId: positiveInteger,
      season: positiveInteger,
      number: positiveInteger,
      title: v.nullable(v.string()),
      airDate: v.nullable(dateSchema)
    }))
  }))
})

type EpisodeSnapshot = v.InferOutput<typeof episodeSnapshotSchema>
type SnapshotSeries = EpisodeSnapshot['series'][number]
type SnapshotEpisode = SnapshotSeries['episodes'][number]

function createSnapshotSeries(source: CatalogEpisodeSource, response: unknown): SnapshotSeries {
  const show = v.parse(showSchema, response)

  const hasExpectedIdentity = show.id === source.showId
    && show.name === source.title
    && show.premiered === source.premiered
    && show.language === source.language

  if (!hasExpectedIdentity) {
    throw new Error(`TVMaze identity changed for ${source.title} (${source.showId}); review the mapping`)
  }

  const episodes: SnapshotEpisode[] = []
  const coordinates = new Set<string>()
  const sourceIds = new Set<number>()
  const { _embedded: embedded } = show

  for (const raw of embedded.episodes) {
    const { type } = v.parse(v.object({ type: v.string() }), raw)

    if (type === 'regular') {
      const episode = v.parse(episodeSchema, raw)

      if (source.seasonRestriction === null || episode.season === source.seasonRestriction) {
        const coordinate = `${episode.season}/${episode.number}`

        if (coordinates.has(coordinate) || sourceIds.has(episode.id)) {
          throw new Error(`Duplicate TVMaze episode for ${source.title}: ${coordinate}, ID ${episode.id}`)
        }

        coordinates.add(coordinate)
        sourceIds.add(episode.id)

        episodes.push({
          tvmazeId: episode.id,
          season: episode.season,
          number: episode.number,
          title: episode.name,
          airDate: episode.airdate === '' ? null : episode.airdate
        })
      }
    }
  }

  episodes.sort((first, second) => first.season - second.season || first.number - second.number)

  return {
    source,
    episodes
  }
}

function sqlText(value: string | null): string {
  if (value === null) {
    return 'NULL'
  }

  const escaped = value.replaceAll('\'', '\'\'')

  return `'${escaped}'`
}

// This offline migration retains row IDs and rejects changed episode identities.
function renderEpisodeMigration(snapshot: EpisodeSnapshot): string {
  v.parse(dateSchema, snapshot.checkedOn)

  const sources: string[] = []
  const episodes: string[] = []
  const showIds = new Set<number>()
  const episodeIds = new Set<number>()

  for (const series of snapshot.series) {
    const { source } = series

    if (showIds.has(source.showId)) {
      throw new Error(`Duplicate TVMaze show ID ${source.showId}`)
    }

    showIds.add(source.showId)

    const title = sqlText(source.title)

    sources.push(`  (${source.showId}, ${title}, ${source.year})`)

    for (const episode of series.episodes) {
      if (episodeIds.has(episode.tvmazeId)) {
        throw new Error(`Duplicate TVMaze episode ID ${episode.tvmazeId}`)
      }

      episodeIds.add(episode.tvmazeId)

      const episodeTitle = sqlText(episode.title)
      const airDate = sqlText(episode.airDate)

      episodes.push(`  (${source.showId}, ${episode.tvmazeId}, ${episode.season}, ${episode.number}, ${episodeTitle}, ${airDate})`)
    }
  }

  if (sources.length === 0) {
    throw new Error('An episode snapshot must include reviewed series')
  }

  const sourceRows = sources.join(',\n')
  const episodeRows = episodes.join(',\n')

  const episodeInsert = episodes.length === 0 ? '' : `
INSERT INTO tv_episode_snapshot_rows VALUES
${episodeRows};
--> statement-breakpoint
`

  return `-- TVMaze episode snapshot checked ${snapshot.checkedOn}.
-- Source: https://www.tvmaze.com/ | https://www.tvmaze.com/api#licensing (CC BY-SA).
-- Generated by catalog:episodes:generate. Review with docs/catalog-content.md.
CREATE TEMPORARY TABLE tv_episode_snapshot_sources (
  show_id integer PRIMARY KEY,
  title text NOT NULL,
  release_year integer NOT NULL,
  catalog_item_id uuid
) ON COMMIT DROP;
--> statement-breakpoint
INSERT INTO tv_episode_snapshot_sources (show_id, title, release_year) VALUES
${sourceRows};
--> statement-breakpoint
DO $$
BEGIN
  IF EXISTS (
    SELECT source.show_id
    FROM tv_episode_snapshot_sources AS source
    LEFT JOIN catalog_item_titles AS title
      ON title.title = source.title AND title.locale = 'en'
    LEFT JOIN catalog_items AS item
      ON item.id = title.catalog_item_id AND item.type = 'series' AND item.release_year = source.release_year
    GROUP BY source.show_id
    HAVING count(item.id) <> 1
  ) THEN
    RAISE EXCEPTION 'expected exactly one catalog series for every reviewed TVMaze mapping';
  END IF;
END $$;
--> statement-breakpoint
UPDATE tv_episode_snapshot_sources AS source
SET catalog_item_id = item.id
FROM catalog_items AS item
JOIN catalog_item_titles AS title ON title.catalog_item_id = item.id
WHERE item.type = 'series' AND item.release_year = source.release_year
  AND title.title = source.title AND title.locale = 'en';
--> statement-breakpoint
CREATE TEMPORARY TABLE tv_episode_snapshot_rows (
  show_id integer NOT NULL REFERENCES tv_episode_snapshot_sources (show_id),
  tvmaze_episode_id integer PRIMARY KEY,
  season_number integer NOT NULL,
  episode_number integer NOT NULL,
  source_title text,
  air_date date,
  UNIQUE (show_id, season_number, episode_number)
) ON COMMIT DROP;
--> statement-breakpoint
${episodeInsert}DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM tv_episode_snapshot_rows AS snapshot
    JOIN tv_episode_snapshot_sources AS source USING (show_id)
    JOIN catalog_episodes AS existing USING (tvmaze_episode_id)
    WHERE existing.catalog_item_id <> source.catalog_item_id
      OR existing.season_number <> snapshot.season_number
      OR existing.episode_number <> snapshot.episode_number
  ) THEN
    RAISE EXCEPTION 'TVMaze episode identity changed; review the snapshot before migrating';
  END IF;
END $$;
--> statement-breakpoint
INSERT INTO catalog_episodes (
  catalog_item_id, tvmaze_episode_id, season_number, episode_number, source_title, air_date
)
SELECT source.catalog_item_id, snapshot.tvmaze_episode_id, snapshot.season_number,
  snapshot.episode_number, snapshot.source_title, snapshot.air_date
FROM tv_episode_snapshot_rows AS snapshot
JOIN tv_episode_snapshot_sources AS source USING (show_id)
ON CONFLICT (tvmaze_episode_id) DO UPDATE
SET source_title = EXCLUDED.source_title, air_date = EXCLUDED.air_date;
--> statement-breakpoint
DROP TABLE tv_episode_snapshot_rows, tv_episode_snapshot_sources;
`
}

export {
  createSnapshotSeries,
  episodeSnapshotSchema,
  renderEpisodeMigration,
  type EpisodeSnapshot,
  type SnapshotSeries
}
